name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment with a supported version
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1'  # Update to a supported version

      # Install dependencies including gh-pages
      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev gh-pages

      # Configure Git user for the CI environment
      - name: Set up Git user
        run: |
          git config --global user.email "y.honey0128@gmail.com"  # Replace with your email
          git config --global user.name "GitHub Actions"  # This can be any name

      # Build the Astro project
      - name: Build project
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: npm run deploy
